.PHONY: clean All

All:
	@echo "----------Building project:[ AssemblyFour - Debug ]----------"
	@cd "AssemblyFour" && "$(MAKE)" -f  "AssemblyFour.mk"
clean:
	@echo "----------Cleaning project:[ AssemblyFour - Debug ]----------"
	@cd "AssemblyFour" && "$(MAKE)" -f  "AssemblyFour.mk" clean
